# specify the projectile option twice
projectile = Pb
projectile = Pb
number-events = 1001

# don't print event properties to stdout, save to text file
quiet = true
output = PbPb

reduced-thickness = 0.063
fluctuation = 1
nucleon-width = 1.19
constit-width = 1.19
constit-number = 1
nucleon-min-dist = 1.37
cross-section = 6.28
normalization = 15.6
random-seed = 361713
# leave commented out for min-bias
# b-min =
# b-max =

grid-max = 14
grid-step = 0.1
